services:
  relay:
    image: ennisj/blobster-relay
    ports:
      - 8109:8109
  test:
    build:
      context: .
      dockerfile: ./docker/relay-test.dockerfile
    command: npm run test
    environment:
      - BLOBSTER_HOST=http://relay:8108
